name: 🚀 Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

env:
  NODE_VERSION: '18.x'

jobs:
  # ============================================================
  # Job 1: Build & Deploy to Firebase
  # ============================================================
  deploy:
    name: 🔥 Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm run test:ci
        env:
          CI: true

      - name: 🏗️ Build application
        run: npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          GENERATE_SOURCEMAP: false

      - name: 🔥 Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: 📊 Deployment Summary
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🌐 URL: https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app"

  # ============================================================
  # Job 2: Deploy Firestore Rules & Indexes
  # ============================================================
  deploy-firestore:
    name: 🗄️ Deploy Firestore Rules
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🗄️ Deploy Firestore rules and indexes
        run: |
          firebase deploy --only firestore:rules,firestore:indexes --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}

      - name: ✅ Firestore deployment complete
        run: echo "✅ Firestore rules and indexes deployed successfully!"

